
from enum import IntEnum
from typing import NamedTuple, Optional
from BaseClasses import Item, ItemClassification

class EBF5Item(Item):
    game: str = "Epic Battle Fantasy 5"

# TODO: Add SID to all items, use instead of Names, maybe use a constant dict for Name to SIDs (eg KH2)
# TODO: Item Ids need to be completely reset.
 
class EBF5ItemCategory(IntEnum): 
    KEY_ITEM        = 1
    KEY             = 2  # as in keys for blocks
    QUEST           = 3  # quest rewards
    SHOP            = 4  # appears in a shop
    SEASONAL        = 5
    EQUIPMENT       = 6
    SWORD           = 7
    STAFF           = 8
    GUN             = 9
    BOW             = 10
    TOY             = 11
    MALE_HATS       = 12
    MALE_ARMOR      = 13
    FEMALE_HATS     = 14
    FEMALE_ARMOR    = 15
    FLAIR           = 16
    CARD            = 19
    SKILL           = 20
    LIMIT_BREAK     = 21
    CRAFTING        = 22
    FOOD            = 23
    BOOSTER         = 24

class ItemData(NamedTuple):
    id: Optional[int]
    game_id: str # name of the static var in the game files
    category: list[EBF5ItemCategory]
    classification: ItemClassification
    is_unique: bool = True
    max_amount: int = 1 # 0 max_amount means no limit

progression = [
    # Progression Checks, Probably wont be used?
    ItemData(None, "Post-Jotun", [], ItemClassification.progression),
    ItemData(None, "Post-Neon Valkyrie", [], ItemClassification.progression),
    ItemData(None, "Post-Laurelin", [], ItemClassification.progression),
    ItemData(None, "Post-Poseidon", [], ItemClassification.progression),
    ItemData(None, "Defeated Sol & Skadi", [], ItemClassification.progression),
    ItemData(None, "Defeated Neon Valhalla", [], ItemClassification.progression),
    ItemData(None, "Defeated Telperion", [], ItemClassification.progression),
    ItemData(None, "Defeated Vulcan", [], ItemClassification.progression),
    ItemData(None, "Defeated Crystal Hydra", [], ItemClassification.progression),
]

equipment = {
    # "Ultra Pro 9000X"       : ItemData(XXXX, "ultrapro9000", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful) # Starting Equipment, not included
    "Heaven's Gate"         : ItemData(5035, "heavensgate", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Berzerker"             : ItemData(5036, "berzerker", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Inferno"               : ItemData(5037, "inferno", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Ice Needle"            : ItemData(5038, "iceneedle", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Lightning Shard"       : ItemData(5039, "lightningbolt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Sapphire Saint"        : ItemData(5040, "sapphiresaint", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Black Fang"            : ItemData(5041, "poisonfang", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "The Chopper"           : ItemData(5042, "chopper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Giant Slayer"          : ItemData(5043, "giantslayer", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Hyper Drill"           : ItemData(5044, "hyperdrill", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Emerald Smasher"       : ItemData(5045, "emeraldsmasher", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Devil's Fork"          : ItemData(5046, "devilsfork", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Club of Withering"     : ItemData(5047, "clubofwithering", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Crimson Razorback"     : ItemData(5048, "crimsonrazorback", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Dragon's Feather"      : ItemData(5049, "dragonfeather", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Golden Axe"            : ItemData(5050, "goldenaxe", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Dark Stalker"          : ItemData(5051, "darkstalker", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Fusion Blade"          : ItemData(5052, "fusionblade", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Soul Eater"            : ItemData(5053, "souleater", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD], ItemClassification.useful),
    "Love Blade"            : ItemData(5054, "loveblade", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.SWORD, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    # "Dark Tooth"            : ItemData(XXXX, "darktooth", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful), # Starting Equipment, not included
    "Sol Spear"             : ItemData(5055, "solspear", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Arctic Trident"        : ItemData(5056, "arctictrident", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Wrath of Zeus"         : ItemData(5057, "zeuswrath", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Druid Staff"           : ItemData(5058, "druidstaff", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Nimbus Rod"            : ItemData(5059, "nimbusrod", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Dragon Wings"          : ItemData(5060, "dragonwings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Gigavolt"              : ItemData(5061, "gigavolt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Alchemy Set"           : ItemData(5062, "alchemyset", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Kaladanda"             : ItemData(5063, "kaladanda", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Wrecking Rod"          : ItemData(5064, "wreckingrod", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Elder's Wisdom"        : ItemData(5065, "elderswisdom", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Obsidian Staff"        : ItemData(5066, "obsidianstaff", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Celtic Cross"          : ItemData(5067, "celticcross", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "The Knife"             : ItemData(5068, "knife", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Paper Fan"             : ItemData(5069, "paperfan", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Oak Staff"             : ItemData(5070, "oakstaff", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Beholding Eye"         : ItemData(5071, "beholdingeye", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Soul Crusher"          : ItemData(5072, "soulcrusher", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Shooting Star"         : ItemData(5073, "shootingstar", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF], ItemClassification.useful),
    "Slime Staff"           : ItemData(5074, "slimestaff", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.STAFF, EBF5ItemCategory.SHOP, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    # "Shadow Blaster"         : ItemData(XXXX, "shadowblaster", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful), # Starting Equipment, not included
    "Nitro Bomber XL"       : ItemData(5075, "nitrobomber", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Hellfire Shotgun"      : ItemData(5076, "hellfireshotgun", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Thunder Core"          : ItemData(5077, "thundercore", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Deep Blue"             : ItemData(5078, "deepblue", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Chainsaw Gun"          : ItemData(5079, "chainsawgun", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Vortex Cannon"         : ItemData(5080, "vortexcannon", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Sub Zero"              : ItemData(5081, "subzero", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Biohazard Blaster"     : ItemData(5082, "biohazardblaster", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Crystal Wing"          : ItemData(5083, "crystalwing", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Heavy Claw"            : ItemData(5084, "heavyclaw", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Soul Pistol"           : ItemData(5085, "soulpistol", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Super Snipe ZX"        : ItemData(5086, "supersnipe", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Coconut Shooter"       : ItemData(5087, "coconutshooter", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Flame Titan"           : ItemData(5088, "flametitan", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Heartstopper"          : ItemData(5089, "heartstopper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Gungnir"               : ItemData(5090, "gungnir", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Spine Snapper"         : ItemData(5091, "spinesnapper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Desert Scorpion"       : ItemData(5092, "desertscorpion", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Accelerator"           : ItemData(5093, "accelerator", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    "Green Goliath"         : ItemData(5094, "greengoliath", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.GUN], ItemClassification.useful),
    # "Fairy Bow"             : ItemData(XXXX, "fairybow", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful), # Starting Equipment, not included
    "Cold Steel"            : ItemData(5095, "coldsteel", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Thor's Hammer"         : ItemData(5096, "thorshammer", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Aquamarine"            : ItemData(5097, "aquamarine", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Gaia's Gift"           : ItemData(5098, "gaiasgift", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Crimson Dragon"        : ItemData(5099, "crimsondragon", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Iron Tusk"             : ItemData(5100, "irontusk", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Fenrir's Jaw"          : ItemData(5101, "Fenrir's Jaw", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "The Deceased"          : ItemData(5102, "thedeceased", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Juggernaut"            : ItemData(5103, "juggernaught", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Emerald Cyclone"       : ItemData(5104, "emeraldcyclone", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Eagle Eye"             : ItemData(5105, "eagleeye", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "The Stinger"           : ItemData(5106, "The Stinger", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Chieftain's Horns"     : ItemData(5107, "Chieftain's Horns", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Regal Turtle"          : ItemData(5108, "Regal Turtle", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Alchemist's Bow"       : ItemData(5109, "Alchemist's Bow", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Black Widow"           : ItemData(5110, "Black Widow", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Angel Wing"            : ItemData(5111, "Angel Wing", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Sharanga"              : ItemData(5112, "Sharanga", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Earth's Whisper"       : ItemData(5113, "Earth's Whisper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW], ItemClassification.useful),
    "Heaven's Voice"        : ItemData(5114, "Heaven's Voice", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.BOW, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    # "Steel Buckler"         : ItemData(XXXX, "steelbuckler", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful), # Starting Equipment, not included
    "Bandit Blade"          : ItemData(5115, "banditblade", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Neon Lightbulb"        : ItemData(5116, "neonlightbulb", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Honjo Masamune"        : ItemData(5117, "masamune", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Riot Shield"           : ItemData(5118, "riotshield", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Leaf Shield"           : ItemData(5119, "leafshield", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Star Hammer"           : ItemData(5120, "starhammer", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Dog Sausage"           : ItemData(5121, "dogsausage", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Icecream Sandwich"     : ItemData(5122, "icecreamsandwich", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Godly Book"            : ItemData(5123, "godlybook", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Human Skull"           : ItemData(5124, "humanskull", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Blood Bank"            : ItemData(5125, "bloodbank", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Viking Buckler"        : ItemData(5126, "vikingbuckler", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Turtle Shell"          : ItemData(5127, "turtleshell", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Elven Shield"          : ItemData(5128, "elvenshield", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Pixel Popper"          : ItemData(5129, "pixelpopper", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Book of Spells"        : ItemData(5130, "bookofspells", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Power Paw"             : ItemData(5131, "powerpaw", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Devil's Sunrise"       : ItemData(5132, "devilssunrise", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "King's Guard"          : ItemData(5133, "kingsguard", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    "Buster Sword"          : ItemData(5134, "bustersword", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.TOY], ItemClassification.useful),
    # "Captain's Hat"         : ItemData(XXXX, "captainhat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful), # Starting Equipment, not included
    # "Knight's Helmet"       : ItemData(XXXX, "knighthelmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful), # Starting Equipment, not included
    # "Officer's Hat"         : ItemData(XXXX, "officerhat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful), # Starting Equipment, not included
    "Horned Helmet"         : ItemData(5135, "hornedhelmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Spartan Helmet"        : ItemData(5136, "spartanhelmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Genji Helmet"          : ItemData(5137, "genjihelmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Basket Hat"            : ItemData(5138, "baskethat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Dragon Helm"           : ItemData(5139, "dragonhelm", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Army Helmet"           : ItemData(5140, "armyhelmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Space Helmet"          : ItemData(5141, "spacehelmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Scottish Cap"          : ItemData(5142, "scottishcap", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Spelunking Hat"        : ItemData(5143, "spelunkinghat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Wizard Hat"            : ItemData(5144, "wizardhat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Headband"              : ItemData(5145, "headband", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Necromancer's Helmet"  : ItemData(5146, "necromandershelmet", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Cardboard Box"         : ItemData(5147, "cardboardbox", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Gas Mask"              : ItemData(5148, "gasmask", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Death Mask"            : ItemData(5149, "deathmask", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Puppy Hat"             : ItemData(5150, "puppyhat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS], ItemClassification.useful),
    "Pumpkin Head"          : ItemData(5151, "pumpkinhead", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Santa Hat"             : ItemData(5152, "santahat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_HATS, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful),
    # "Hobo Clothes"          : ItemData(XXXX, "hoboclothes", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful), # Starting Equipment, not included
    # "Heroic Armor"          : ItemData(XXXX, "heroicarmor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful), # Starting Equipment, not included
    # "Officer's Coat"        : ItemData(XXXX, "officercoat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful), # Starting Equipment, not included
    "Captain's Coat"        : ItemData(5153, "captainscoat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Viking Fur"            : ItemData(5154, "vikingfur", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Spartan Cuirass"       : ItemData(5155, "spartancuirass", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Genji Armor"           : ItemData(5156, "genjiarmor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Ninja Gear"            : ItemData(5157, "ninjagear", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Dragon Armor"          : ItemData(5158, "dragonarmor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Camo Jacket"           : ItemData(5159, "camojacket", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Space Ace"             : ItemData(5160, "spaceace", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Scottish Kilt"         : ItemData(5161, "scottishkilt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Explorer's Jacket"     : ItemData(5162, "explorersjacket", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Wizard Robe"           : ItemData(5163, "wizardrobe", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Turtle Gi"             : ItemData(5164, "turtlegi", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Flame Suit"            : ItemData(5165, "flamesuit", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Hipster Shirt"         : ItemData(5166, "hipstershirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Shell Armor"           : ItemData(5167, "shellarmor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Priest's Tunic"        : ItemData(5168, "prieststunic", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR], ItemClassification.useful),
    "Coat of Teeth"         : ItemData(5169, "coatoftheeth", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    "Santa Outfit"          : ItemData(5170, "santaoutfit", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.MALE_ARMOR, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    # "Red Ribbon"            : ItemData(XXXX, "redribbon", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful), # Starting Equipment, not included
    # "Amber Bobble"          : ItemData(XXXX, "fierybobble", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful), # Starting Equipment, not included
    "Nurse Hat"             : ItemData(5171, "nursehat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Fur Hat"               : ItemData(5172, "furhat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Pope Hat"              : ItemData(5173, "popehat", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Leafy Hairclip"        : ItemData(5174, "leafyhairclip", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Curly Horns"           : ItemData(5175, "curlyhorns", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Cat Ears"              : ItemData(5176, "kittyears", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Flower Bobble"         : ItemData(5177, "flowerbobble", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Dark Bobble"           : ItemData(5178, "darkbobble", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Slime Bunny"           : ItemData(5179, "slimebunny", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Ninja Chopsticks"      : ItemData(5180, "ninjachopsticks", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Robot Ears"            : ItemData(5181, "robotears", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Drill Bits"            : ItemData(5182, "drillbits", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Bunny Ears"            : ItemData(5183, "bunnyears", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Ice Shards"            : ItemData(5184, "iceshards", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Royal Crown"           : ItemData(5185, "royalcrown", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Rubber Duck"           : ItemData(5186, "rubberduck", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Blue Elephant"         : ItemData(5187, "blueelephant", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS], ItemClassification.useful),
    "Spider Bobble"         : ItemData(5188, "spiderbobble", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Holly Hairpin"         : ItemData(5189, "hollyhairpin", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_HATS, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful),
    # "Red Dress"            : ItemData(XXXX, "reddress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful), # Starting Equipment, not included
    # "Ranger Skirt"         : ItemData(XXXX, "rangerskirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful), # Starting Equipment, not included
    "Nurse Uniform"         : ItemData(5190, "nurseuniform", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Fur Dress"             : ItemData(5191, "furdress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Pope Dress"            : ItemData(5192, "popedress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Cactus Dress"          : ItemData(5193, "cactusdress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Cow Costume"           : ItemData(5194, "cowcostume", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Maid Outfit"           : ItemData(5195, "maidoutfit", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Summer Kimono"         : ItemData(5196, "summerkimono", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Dark Gown"             : ItemData(5197, "darkgown", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Magical Skirt"         : ItemData(5198, "magicalskirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Ninja Skirt"           : ItemData(5199, "ninjaskirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Mecha Suit"            : ItemData(5200, "mechasuit", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Obsidian Armor"        : ItemData(5201, "obsidianarmor", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "School Uniform"        : ItemData(5202, "schooluniform", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Bubble Dress"          : ItemData(5203, "bubblydress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Camo Skirt"            : ItemData(5204, "camoskirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Sami Dress"            : ItemData(5205, "samidress", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Casual Skirt"          : ItemData(5206, "casualskirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR], ItemClassification.useful),
    "Spider Gown"           : ItemData(5207, "spidergown", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    "Santa Skirt"           : ItemData(5208, "santaskirt", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FEMALE_ARMOR, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    "Flame Badge"           : ItemData(5209, "flamebadge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Lightning Badge"       : ItemData(5210, "lightningbadge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Frost Badge"           : ItemData(5211, "frostbadge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Pearl Necklace"        : ItemData(5212, "pearlnecklace", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Surgical Mask"         : ItemData(5213, "surgicalmask", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Angel Pin"             : ItemData(5214, "angelpin", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Bandage"               : ItemData(5215, "bandage", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Iron Cross"            : ItemData(5216, "ironcross", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Silver Cross"          : ItemData(5217, "silvercross", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Golden Pendant"        : ItemData(5218, "goldenpendant", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Nano Machines"         : ItemData(5219, "nanomachines", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Battle Paint"          : ItemData(5220, "battlepaint", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Lucky Clover"          : ItemData(5221, "luckyclover", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Hoop Earrings"         : ItemData(5222, "hoopearrings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "The Tr*force"          : ItemData(5223, "thetriforce", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Green Cross"           : ItemData(5224, "greencross", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Fairy"                 : ItemData(5225, "fairy", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Pocket Watch"          : ItemData(5226, "pocketwatch", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Meow Meow Badge"       : ItemData(5227, "meowmeowbadge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Captain Viridian"      : ItemData(5228, "captainviridian", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Agnry Faic"            : ItemData(5229, "agnryfaic", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Target Badge"          : ItemData(5230, "targetbadge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Tentacle"              : ItemData(5231, "tentacle", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Peace Badge"           : ItemData(5232, "peacebadge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Crossbone Pin"         : ItemData(5233, "crossbonepin", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Chrome Earrings"       : ItemData(5234, "chromeearrings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Amethyst Earrings"     : ItemData(5235, "amethysteearrings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Emerald Earrings"      : ItemData(5236, "emeraldearrings", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Fat Fly"               : ItemData(5237, "fatfly", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Bitey Badge"           : ItemData(5238, "biteybadge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Baby Penguin"          : ItemData(5239, "babypenguin", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Pet Rock"              : ItemData(5240, "petrock", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Tetromino"             : ItemData(5241, "tetromino", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Pixel Glasses"         : ItemData(5242, "pixelglasses", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Fake Mustache"         : ItemData(5243, "fakemustache", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Big Eyebrows"          : ItemData(5244, "bigeyebrows", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "RAM Chip"              : ItemData(5245, "ramchip", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Juicy Beast"           : ItemData(5246, "juicybeast", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Small Cloud"           : ItemData(5247, "smallcloud", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Dinosaur Egg"          : ItemData(5248, "dinosauregg", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Lucky Fish"            : ItemData(5249, "luckyfish", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "Coin Charm"            : ItemData(5250, "coincharm", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    "Mini Drone"            : ItemData(5251, "minidrone", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Heart Pendant"         : ItemData(5252, "heartpendant", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR, EBF5ItemCategory.SEASONAL, EBF5ItemCategory.SHOP], ItemClassification.useful),
    "The One R*ng"          : ItemData(5253, "theonering", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Companion C*be"        : ItemData(5254, "companioncube", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Dog Tags"              : ItemData(5255, "dogtags", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Narutomaki"            : ItemData(5256, "narutomaki", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Cat Tail"              : ItemData(5257, "cattail", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Tooth"                 : ItemData(5258, "tooth", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Balance Badge"         : ItemData(5259, "balancebadge", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Sword Medal"           : ItemData(5260, "swordmedal", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Shield Medal"          : ItemData(5261, "shieldmedal", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Gold Star"             : ItemData(5262, "goldstar", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
    "Platinum Star"         : ItemData(5263, "platinumstar", [EBF5ItemCategory.EQUIPMENT, EBF5ItemCategory.FLAIR], ItemClassification.useful),
}

cards = {
    "Card 01 (Baby Bush)": ItemData(5264, "card1", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 02 (Big Bush)": ItemData(5265, "card2", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 03 (Bazooka Bush)": ItemData(5266, "card3", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 04 (Creepy Idol)": ItemData(5267, "card4", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 05 (Undead Boulder)": ItemData(5268, "card5", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 06 (Snarky Radish)": ItemData(5269, "card6", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 07 (Snarky Tree)": ItemData(5270, "card7", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 08 (Eyeball Plant)": ItemData(5271, "card8", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 09 (Beholding Bat)": ItemData(5272, "card9", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 10 (Beholding Beast)": ItemData(5273, "card10", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 11 (Potted Gloop)": ItemData(5274, "card11", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 12 (Crystal Gloop)": ItemData(5275, "card12", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 13 (Sandstone Gloop)": ItemData(5276, "card13", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 14 (Famine Face)": ItemData(5277, "card14", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 15 (Frosty Face)": ItemData(5278, "card15", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 16 (Fire Face)": ItemData(5279, "card16", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 17 (Cursed Medallion)": ItemData(5280, "card17", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 18 (Cursed Chest)": ItemData(5281, "card18", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 19 (Spy Satellite)": ItemData(5282, "card19", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 20 (Flybot Drone)": ItemData(5283, "card20", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 21 (Lava Slime)": ItemData(5284, "card21", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 22 (Magma Slime)": ItemData(5285, "card22", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 23 (Volcano Slime)": ItemData(5286, "card23", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 24 (Touchy Octopus)": ItemData(5287, "card24", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 25 (Angry Bee)": ItemData(5288, "card25", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 26 (Fighter Bee)": ItemData(5289, "card26", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 27 (Mountain Goat)": ItemData(5290, "card27", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 28 (Chibi Robot)": ItemData(5291, "card28", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 29 (Dai Robot)": ItemData(5292, "card29", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 30 (Normal Turtle)": ItemData(5293, "card30", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 31 (Derpy Turtle)": ItemData(5294, "card31", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 32 (Titanic Turtle)": ItemData(5295, "card32", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 33 (Sea Jelly)": ItemData(5296, "card33", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 34 (Electron Child)": ItemData(5297, "card34", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 35 (Electron Cloud)": ItemData(5298, "card35", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 36 (Electron Knight)": ItemData(5299, "card36", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 37 (Sacred Guardian)": ItemData(5300, "card37", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 38 (Evil Fungus)": ItemData(5301, "card38", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 39 (Ice Mite)": ItemData(5302, "card39", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 40 (Ice Roach)": ItemData(5303, "card40", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 41 (Pupper)": ItemData(5304, "card41", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 42 (Doggo)": ItemData(5305, "card42", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 43 (Specter)": ItemData(5306, "card43", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 44 (Hollow Soldier)": ItemData(5307, "card44", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 45 (Fire Elemental)": ItemData(5308, "card45", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 46 (Donut Snake)": ItemData(5309, "card46", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 47 (Toaster)": ItemData(5310, "card47", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 48 (Baby Bacon)": ItemData(5311, "card48", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 49 (Bacon Roll)": ItemData(5312, "card49", [EBF5ItemCategory.CARD], ItemClassification.useful),
    "Card 50 (Adult Bacon)": ItemData(5313, "card50", [EBF5ItemCategory.CARD], ItemClassification.useful),
}

skills = [
    ItemData(5314, "Ivy", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5315, "Acid", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5316, "Gale", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5317, "Shock", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5318, "Sand", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5319, "Bullet Bob", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5320, "Purging Flame", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5321, "Giga Drill", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5322, "Electron Gun", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5323, "Bubble Ring", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5324, "Gaia Seed", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5325, "Bubble", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5326, "Air", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5327, "Energy", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5328, "Sawblade", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5329, "Snow Bunnies", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5330, "Fire Spin", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5331, "Fairy Bombs", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5332, "Demon Swords", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5333, "Geometry", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5334, "Encore", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5335, "Power Metal", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5336, "Screamer", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5337, "The Reaper", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5338, "Lock On", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5339, "Heavenly Shield", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5340, "Reflex", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5341, "Enfeeble", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5342, "Sharpen", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5343, "Bind", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5344, "Flare", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5345, "Revive", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5346, "Purify", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5347, "Phyrnna's Blessing", [EBF5ItemCategory.SKILL], ItemClassification.useful),
    ItemData(5348, "Firecrackers", [EBF5ItemCategory.SKILL, EBF5ItemCategory.SEASONAL], ItemClassification.useful),
    ItemData(5349, "Annihalate", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
    ItemData(5350, "Supernova", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
    ItemData(5351, "Absolute Zero", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
    ItemData(5352, "Tsunami", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
    ItemData(5353, "Black Hole", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
    ItemData(5354, "Seven Swords", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
    ItemData(5355, "Death Metal", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
    ItemData(5356, "Hidden Power", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
    ItemData(5357, "Art Attack", [EBF5ItemCategory.LIMIT_BREAK], ItemClassification.useful),
]

crafting_items = [
    ItemData(5358, "snowball", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5359, "wool", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5360, "brick", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5361, "turd", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5362, "seashell", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5363, "cactus", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5364, "iron", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5365, "shuriken", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5366, "feather", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5367, "flower", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5368, "spring", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5369, "wood", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5370, "bomb", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5371, "herb", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5372, "pipe", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5373, "tape", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5374, "geode", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5375, "root", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5376, "powder", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5377, "glass", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5378, "fur", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5379, "butterflywing", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5380, "gems", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5381, "ice", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5382, "water", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5383, "buckle", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5384, "steel", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5385, "magma", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5386, "floppy", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5387, "silk", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5388, "gear", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5389, "plastic", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5390, "amber", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5391, "leather", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5392, "virus", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5393, "claw", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5394, "rune2", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5395, "spike", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5396, "silver", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5397, "satin", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5398, "ruby", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5399, "topaz", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5400, "sapphire", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5401, "emerald", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5402, "gold", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5403, "rune", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5404, "cpu", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5405, "kevlar", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5406, "opal", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5407, "lego", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5408, "moonpearl", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5409, "scales", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5410, "gamechild", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5411, "titanium", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5412, "diamond", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5413, "darkmatter", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5414, "plutonium", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5415, "grail", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5416, "mythril", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
    ItemData(5417, "starfragment", [EBF5ItemCategory.CRAFTING], ItemClassification.filler),
]

food = [
    ItemData(5418, "pumpkin", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5419, "pineapple", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5420, "watermelon", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5421, "dragonfruit", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5422, "raspberries", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5423, "blueberries", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5424, "cloudberries", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5425, "garlic", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5426, "banana", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5427, "pretzel", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5428, "apple", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5429, "cupcake", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5430, "beer", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5431, "cola", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5432, "bru", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5433, "energy", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5434, "coffee", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5435, "espresso", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5436, "chili", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5437, "orangejuice", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5438, "crisps", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5439, "chips", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5440, "burger", [EBF5ItemCategory.FOOD], ItemClassification.filler),
    ItemData(5441, "pizza", [EBF5ItemCategory.FOOD], ItemClassification.filler),
]

boosters = [
    ItemData(5442, "bacon", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5443, "beef", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5444, "chicken", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5445, "egg", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5446, "poptart", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5447, "donut", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5448, "cake", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5449, "lollipop", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5450, "bread", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5451, "potato", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5452, "pill", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5453, "mushroom", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5454, "turnip", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5455, "grapes", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5456, "mint", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5457, "nut", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5458, "sushi", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5459, "riceball", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5460, "yoghurt", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
    ItemData(5461, "milk", [EBF5ItemCategory.BOOSTER], ItemClassification.filler),
]

key_items = [
    # TODO: Label Quest Items
    # TODO: Consider which items can be tagged as progressions_skip_balancing (eg: the four orbs and three jewels)
    # TODO: Consider which items can be tagged as both progression AND useful
    ItemData(5462, "scouter", [EBF5ItemCategory.KEY_ITEM], ItemClassification.filler),                  # Starting Item TODO: Check if actually tied to logic
    ItemData(5463, "oldboots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.filler),                 # Starting Item TODO: Check if actually tied to logic
    ItemData(5464, "magneticboots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5465, "leafyboots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5466, "spikedboots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5467, "thermalboots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5468, "wingedboots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5469, "rubberboots", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5470, "hammer", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5471, "bighammer", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5472, "axe", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5473, "shovel", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5474, "stepladder", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5475, "raft", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5476, "candle", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),               # Check if actually a progression item
    ItemData(5477, "fishingrod", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5478, "map", [EBF5ItemCategory.KEY_ITEM], ItemClassification.filler),                       # Starting Item TODO: Check if actually tied to logic
    ItemData(5479, "map2", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),                      # Red Envelope
    ItemData(5480, "woodenkey", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, False, 5),
    ItemData(5481, "coralkey", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, False, 6),
    ItemData(5482, "topazkey", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, False, 4),
    ItemData(5483, "copperkey", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, False, 4),
    ItemData(5484, "goldkey", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, False, 6),
    ItemData(5485, "diamondkey", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, False, 4),
    ItemData(5486, "flute", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5487, "ocarina", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5488, "starball", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 6),
    ItemData(5489, "musicCD", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 6),
    ItemData(5490, "stick", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 6),
    # ItemData(5491, "plank", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 0),        # NOT A CHECK, dropped by Enemy
    ItemData(5492, "panties", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 4),
    ItemData(5493, "stonehead", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression, False, 6), # prog AND quest item
    ItemData(5494, "earthenware", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 5),
    ItemData(5495, "newspaper", [EBF5ItemCategory.KEY_ITEM], ItemClassification.filler),
    ItemData(5496, "magazine", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5497, "mail", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5498, "popcorn", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 9),
    ItemData(5499, "keycard", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 12),       # Golden Ticket 
    # ItemData(5500, "keycard2", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 0),     # Green Keycard, NOT A CHECK, dropped by Enemy
    ItemData(5501, "emptybottle", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 4),
    ItemData(5502, "milkbottle", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 5),
    ItemData(5503, "lavabottle", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 5),
    ItemData(5504, "waterbottle", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 4),
    ItemData(5505, "darkbottle", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 4),
    ItemData(5506, "holybottle", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 4),
    ItemData(5507, "sunglasses", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 2),
    ItemData(5508, "glasses", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5509, "sock1", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 4),
    ItemData(5510, "sock2", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 4),
    ItemData(5511, "headband", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 5),
    # ItemData(5512, "battery", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 0),      # NOT A CHECK, dropped by Enemy
    ItemData(5513, "poop", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 4),
    ItemData(5514, "cookie", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 9),
    ItemData(5515, "chocolate", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful, False, 5),
    ItemData(5516, "earthorb", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5517, "windorb", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5518, "fireorb", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5519, "waterorb", [EBF5ItemCategory.KEY_ITEM], ItemClassification.progression),
    ItemData(5520, "greenjewel", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5521, "bluejewel", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    ItemData(5522, "redjewel", [EBF5ItemCategory.KEY_ITEM], ItemClassification.useful),
    # Seasonal items
    # ItemData(5523, "halloweencandy", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.SEASONAL], ItemClassification.useful),  # NOT A CHECK, dropped by Enemy
    # ItemData(5524, "candycane", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.SEASONAL], ItemClassification.useful),       # NOT A CHECK, dropped by Enemy
    # ItemData(5525, "valentine", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.SEASONAL], ItemClassification.useful),       # NOT A CHECK, dropped by Enemy
    # ItemData(5526, "easteregg", [EBF5ItemCategory.KEY_ITEM, EBF5ItemCategory.SEASONAL], ItemClassification.useful),       # NOT A CHECK, dropped by Enemy
]
